title: "GNN Explainers 2.0: User-centric and Data-driven Insights"
description: "WSDM 2026 Tutorial"
wsdm_logo: /assets/logos/wsdm.png
theme: jekyll-theme-cayman
logo: /assets/logos/logo1s.png
show_downloads: false
